defmodule TM.Mercury.Parameter do
  # @parameters [
  #   baud_rate: 1,
  #   probe_baud_rates: 2,
  #   command_timeout: 3,
  #   transport_timeout: 4,
  #   powermode: 5,
  #   usermode: 6,
  #   antenna_checkport: 7,
  #   antenna_portlist: 8,
  #   antenna_connectedportlist: 9,
  #   antenna_portswitchgpos: 10,
  #   antenna_settlingtimelist: 11,
  #   antenna_returnloss: 12,
  #   antenna_txrxmap: 13,
  #   gpio_inputlist: 14,
  #   gpio_outputlist: 15,
  #   gen2_accesspassword: 16,
  #   gen2_q: 17,
  #   gen2_tagencoding: 18,
  #   gen2_session: 19,
  #   gen2_target: 20,
  #   gen2_blf: 21,
  #   gen2_tari: 22,
  #   gen2_writemode: 23,
  #   gen2_bap: 24,
  #   iso180006b_blf: 25,
  #   iso180006b_modulation_depth: 26,
  #   iso180006b_delimiter: 27,
  #   read_asyncofftime: 28,
  #   read_asyncontime: 29,
  #   read_plan: 30,
  #   radio_enablepowersave: 40,
  #   radio_powermax: 50,
  #   radio_powermin: 51,
  #   radio_portreadpowerlist: 52,
  #   radio_portwritepowerlist,
  #   radio_readpower,
  #   radio_writepower,
  #   radio_temperature,
  #   tagreaddata_recordhighestrssi,
  #   tagreaddata_reportrssiindbm,
  #   tagreaddata_uniquebyantenna,
  #   tagreaddata_uniquebydata,
  #   tagop_antenna,
  #   tagop_protocol,
  #   version_hardware,
  #   version_serial,
  #   version_model,
  #   version_software,
  #   version_supportedprotocols,
  #   region_hoptable,
  #   region_hoptime,
  #   region_id,
  #   region_supportedregions,
  #   region_lbt_enable,
  #   license_key,
  #   user_config,
  #   radio_enablesjc,
  #   extendedepc,
  #   reader_statistics,
  #   reader_stats,
  #   uri,
  #   product_group_id,
  #   product_group,
  #   product_id,
  #   tagreadata_tagopsuccesscount,
  #   tagreadata_tagopfailurecount,
  #   status_enable_antennareport,
  #   status_enable_frequencyreport,
  #   status_enable_temperaturereport,
  #   tagreaddata_enablereadfilter,
  #   tagreaddata_readfiltertimeout,
  #   tagreaddata_uniquebyprotocol,
  #   reader_description,
  #   reader_hostname,
  #   currenttime,
	#    reader_write_reply_timeout,
	#     reader_write_early_exit,
  #     reader_stats_enable,
  #     trigger_read_gpi,
  # ]

end
